# Generated by Django 3.1 on 2024-12-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
    ]
