# Generated by Django 3.1 on 2024-11-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='talla',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=20),
        ),
    ]
