# Generated by Django 3.1 on 2024-12-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBD', '0002_ventas_anulada'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulomarca',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
