# Generated by Django 3.1.1 on 2024-12-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBD', '0002_auto_20241202_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriacard',
            name='titulo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
